// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtK5OnsDPEbWSRLEldVJWP7nczogOgKpg',
    appId: '1:1084782662457:web:a37650f8978b35f036cee8',
    messagingSenderId: '1084782662457',
    projectId: 'onicars-4ada2',
    authDomain: 'onicars-4ada2.firebaseapp.com',
    storageBucket: 'onicars-4ada2.appspot.com',
    measurementId: 'G-KT6317HNSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzpwZDvc1_m_dJZt684NqqAUNJydbpaXs',
    appId: '1:1084782662457:android:6ea3f0293c6c391436cee8',
    messagingSenderId: '1084782662457',
    projectId: 'onicars-4ada2',
    storageBucket: 'onicars-4ada2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Vqxl7L_cZfq5RYjz2W3DJoAkvB1HxdA',
    appId: '1:1084782662457:ios:f0cfe79413a978ca36cee8',
    messagingSenderId: '1084782662457',
    projectId: 'onicars-4ada2',
    storageBucket: 'onicars-4ada2.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Vqxl7L_cZfq5RYjz2W3DJoAkvB1HxdA',
    appId: '1:1084782662457:ios:37d574f97aa489bb36cee8',
    messagingSenderId: '1084782662457',
    projectId: 'onicars-4ada2',
    storageBucket: 'onicars-4ada2.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
